#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Please enter run number!"
    exit 1
fi

runNum=$1
root -l -b -q $COMPMON_DIR/macros/whatsThePolarization.C\($runNum\)
evince $COMPMON_DIR/macros/plots/polarization_run$runNum.pdf
rm -f $COMPMON_DIR/macros/plots/polarization_run$runNum.pdf
